docker run --rm --name=ODataConnector \
    -e ZEEBE_CLIENT_SECURITY_PLAINTEXT=true \
    -e ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS=192.168.0.83:26500 \
    -e SERVER_PORT=9898 \
    -e CAMUNDA_CONNECTOR_POLLING_ENABLED=false \
    -e CAMUNDA_CLIENT_MODE=simple \
    -e CAMUNDA_CLIENT_AUTH_USERNAME=demo \
    -e CAMUNDA_CLIENT_AUTH_PASSWORD=demo \
    -e CAMUNDA_CLIENT_OPERATE_BASE-URL=http://192.168.0.83:8081 \
    -e TRUST_ALL_CERTS=true \
        camundaodataconnector:0.1.0