name: test-pr

on:
  pull_request:
    branches:
      - release/8.6

jobs:
  build-and-test:
    uses: ./.github/workflows/reusable-build-and-test.yml
    with:
      java-version: '21'
      distribution: 'temurin'
      maven-options: '-PcheckFormat'
      spring_profile: 'integration-c86-saas'
    secrets: inherit