name: test PRs

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: use node 20 
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm' 
    - name: install and run OData v2 + v4 mockserver
      run: |
        cd cap-bookshop
        npm ci
        npm start
        
    - name: set up jdk 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: build and test with maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
