name: reusable-build-and-test

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      distribution:
        required: true
        type: string
      maven-options:
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: use node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'cap-bookshop/package-lock.json'

      - name: install and run OData v2 + v4 mockserver
        run: |
          cd cap-bookshop
          npm i
          npm start &

      - run: cd .. # back to java space...

      - name: set up jdk ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          cache: maven

#      - name: test env var availability
#        env:
#          destinations: ${{ secrets.DESTINATIONS }}
#        run: echo $destinations

      - name: build and test with maven
        env:
          destinations: ${{ secrets.DESTINATIONS }}
        run: mvn -B ${{ inputs.maven-options }} --file pom.xml