name: reusable-deploy

on:
  workflow_call:
    inputs:
      connector_version: # fex: 8.5.7 - 8.5 for Camunda release, 7 for connector version
        required: true
        type: string
      region:
        required: true
        type: string
      cf_api_endpoint:
        required: true
        type: string
      cf_org:
        required: true
        type: string
      cf_space:
        required: true
        type: string

    secrets:
      cluster_id:
        required: true
      client_id:
        required: true
      client_secret:
        required: true
      cf_user:
        required: true
      cf_password:
        required: true

jobs:
  extract-version:
    runs-on: ubuntu-latest
    steps:
      - name: extract release branch # first two digits of connector_version
        run: echo "camunda_release=$(echo ${{ inputs.connector_version }} | cut -d'.' -f1-2)" >> $GITHUB_ENV

#      - name: extract connector version for release # last digit of connector_version
#        run: echo "connector_version=$(echo ${{ inputs.connector_version }} | cut -d'.' -f3)" >> $GITHUB_ENV

  mtad-yaml: # get the mtad.yaml.example from the release branch via sparse checkout
    runs-on: ubuntu-latest
    needs: extract-version
    steps:
      - name: checkout mtad.yaml.example
        uses: actions/checkout@v4
        with:
          repository: camunda/sap-odata-connector
          ref: ${{ env.camunda_release }}
          path: yaml
          sparse-checkout: |
            mtad.yaml.example
          sparse-checkout-cone-mode: false

      - name: check
        run: ls -al yaml

      - name: fill in target cluster credentials
        run: |
          cd yaml
          sed -i -e "s/version:/version: ${{ inputs.connector_version }}/g" \
          -e "s/name: sap-odata-connector/name: sap-odata-connector-${{ inputs.connector_version }}/g" \
          -e "s/ZEEBE_CLIENT_CLOUD_CLUSTER-ID/ZEEBE_CLIENT_CLOUD_CLUSTER-ID: ${{ secrets.cluster_id }}/g" \
          -e "s/ZEEBE_CLIENT_CLOUD_CLIENT-ID/ZEEBE_CLIENT_CLOUD_CLIENT-ID: ${{ secrets.client_id }}/g" \
          -e "s/ZEEBE_CLIENT_CLOUD_CLIENT-SECRET/ZEEBE_CLIENT_CLOUD_CLIENT-SECRET: '${{ secrets.client_secret }}'/g" \
          -e "s/camunda\/sap-odata-connector/camunda\/sap-odata-connector:${{ inputs.connector_version }}/g" \
          -e "s/ZEEBE_CLIENT_CLOUD_REGION/ZEEBE_CLIENT_CLOUD_REGION: ${{ inputs.region }}/g" \
          mtad.yaml.example
          mv mtad.yaml.example mtad.yaml
          cd ..

      - name: check substitution result
        run: |
          ls -al .
          ls -al yaml/mtad.yaml

  deploy:
    needs: mtad-yaml
    runs-on: ubuntu-latest
    container:
      image: cloudfoundry/cli:latest
      volumes:
        - ./yaml:/tmp/yaml
      env:
        connector_version: ${{ inputs.connector_version }}

    steps:
      - name: deploy ${{inputs.connector_version}} to BTP
        run: |
          cf install-plugin multiapps -f
          cd /tmp/yaml
          ls -al /tmp/yaml
          cf login -a ${{ inputs.cf_api_endpoint }} -u ${{ secrets.cf_user }} -p ${{ secrets.cf_password }} -o ${{ inputs.cf_org }} -s ${{ inputs.cf_space }}
          cf deploy ./ -f